server:
  port: 8080

datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: gin_db
  username: root
  password: your_password
  charset: utf8mb4

jwt:
  secret: "your-very-secret-key-here"
  expire: 24 # 过期时间（小时）